### ISSUE TITLE
怎么拓展的？

### ISSUE THREAD

**Issue by yuanjie-ai** [thunlp/Auto_CLIWC#2]
通过更改词向量实现词典拓展？

**Comment by xiangkaiz** [comment]
Basically, we are using a seq2seq model to expand the lexicon. For more details, please refer to our paper: _Xiangkai Zeng, Cheng Yang, Cunchao Tu, Zhiyuan Liu, Maosong Sun. Chinese LIWC Lexicon Expansion via Hierarchical Classification of Word Embeddings with Sememe Attention. The 32nd AAAI Conference on Artificial Intelligence (AAAI 2018)._
