### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by az5872** [thunlp/Auto_CLIWC#8]
ValueError                                Traceback (most recent call last)
<ipython-input-15-f22709bf6d6a> in <module>
      1 word_embeddings = tf.constant(vector_matrix, dtype=tf.float32)
----> 2 sememe_embeddings = tf.constant(memory_matrix, dtype=tf.float32)
      3 sememe_lengths = tf.constant(memory_lengths, dtype=tf.int32)
      4 x = tf.gather(word_embeddings, index_holder)
      5 sememe_memory = tf.gather(sememe_embeddings, index_holder)

d:\Users\Matt\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py in constant(value, dtype, shape, name, verify_shape)
    206   tensor_value.tensor.CopyFrom(
    207       tensor_util.make_tensor_proto(
--> 208           value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    209   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    210   const_tensor = g.create_op(

d:\Users\Matt\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    441     else:
    442       _AssertCompatible(values, dtype)
--> 443       nparray = np.array(values, dtype=np_dt)
    444       # check to them.
    445       # We need to pass in quantized values as tuples, so don't apply the shape

ValueError: setting an array element with a sequence.

**Comment by az5872** [comment]
how to solve this one guys?
I USE my own word embedding

**Comment by xiangkaiz** [comment]
This seems like a wrong initialization matrix problem. Can you double check your initialization matrix?

**Comment by Fanchao-Qi** [comment]
No reply. This issue is closed for now.
