### ISSUE TITLE
词典的来源是什么？

### ISSUE THREAD

**Issue by pinkyaliceyym** [thunlp/Auto_CLIWC#9]
您好！感谢分享的内容。我注意到现有工程里提供的SC-LIWC词典只有5000多词，但是论文中提到的SC-LIWC应该有7000多词。因此本项目中的词典是否有所遗漏词语呢？词典来源于哪个网站呢？LIWC官网现在都需要付费才能使用他们的软件。

**Comment by xiangkaiz** [comment]
根据词典文件：https://github.com/thunlp/Auto_CLIWC/blob/3fd594911cde210cf0d3a06226975449c0c00083/datasets/sc_liwc.dic#L6880
一共有6880行。减去前面的类别定义，和论文中提到的一共6828个词是一致的，词典应该是没有遗漏词语的。具体来源是原始CLIWC网站：https://cliwceg.weebly.com/sc-liwc-dic.html

**Comment by Fanchao-Qi** [comment]
Seems that the question has been properly answered.

**Comment by zhunipingan** [comment]
请问原始词典如何获得，购买软件吗 谢谢
